# Generated by Django 5.2.4 on 2025-07-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Access Type',
                'verbose_name_plural': 'Access Types',
                'db_table': 'access_types',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='LandType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Land Type',
                'verbose_name_plural': 'Land Types',
                'db_table': 'land_types',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Utility',
                'verbose_name_plural': 'Utilities',
                'db_table': 'utilities',
                'ordering': ['display_name'],
            },
        ),
    ]
