# Generated by Django 5.2.4 on 2025-10-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userghlmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='userghlmapping',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
