# Generated by Django 5.2.4 on 2025-08-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('asset_types', models.CharField(choices=[('land', 'Land'), ('houses', 'Houses'), ('both', 'Both')], max_length=20)),
                ('active_buyer', models.BooleanField(default=True)),
                ('blacklist_status', models.BooleanField(default=False)),
                ('cities', models.JSONField(blank=True, null=True)),
                ('counties', models.JSONField(blank=True, null=True)),
                ('states', models.JSONField(blank=True, null=True)),
                ('zips', models.JSONField(blank=True, null=True)),
                ('house_strategies', models.JSONField(blank=True, null=True)),
                ('land_strategies', models.JSONField(blank=True, null=True)),
                ('house_types', models.JSONField(blank=True, null=True)),
                ('land_types', models.JSONField(blank=True, null=True)),
                ('price_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lot_size_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lot_size_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('sqft_min', models.PositiveIntegerField(blank=True, null=True)),
                ('sqft_max', models.PositiveIntegerField(blank=True, null=True)),
                ('year_built_min', models.PositiveIntegerField(blank=True, null=True)),
                ('year_built_max', models.PositiveIntegerField(blank=True, null=True)),
                ('restricted_rehab_types', models.JSONField(blank=True, null=True)),
                ('specialty_rehab_avoidance', models.JSONField(blank=True, null=True)),
                ('legal_access_required', models.BooleanField(default=False)),
                ('utilities_at_road', models.BooleanField(default=False)),
                ('no_flood_zone', models.BooleanField(default=False)),
                ('clear_title', models.BooleanField(default=False)),
                ('no_hoa', models.BooleanField(default=False)),
                ('paved_road_access', models.BooleanField(default=False)),
                ('mobile_home_allowed', models.BooleanField(default=False)),
                ('location_characteristics', models.JSONField(blank=True, null=True)),
                ('property_characteristics', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
