# Generated by Django 5.2.4 on 2025-08-04 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_remove_buyerprofile_active_buyer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyBoxFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('land', 'Land'), ('houses', 'Houses'), ('both', 'Both')], max_length=10)),
                ('is_active_buyer', models.BooleanField(default=True)),
                ('is_blacklisted', models.BooleanField(default=False)),
                ('preferred_cities', models.JSONField(blank=True, default=list)),
                ('preferred_counties', models.JSONField(blank=True, default=list)),
                ('preferred_states', models.JSONField(blank=True, default=list)),
                ('preferred_zip_codes', models.JSONField(blank=True, default=list)),
                ('house_strategies', models.JSONField(blank=True, default=list)),
                ('land_strategies', models.JSONField(blank=True, default=list)),
                ('house_property_types', models.JSONField(blank=True, default=list)),
                ('land_property_types', models.JSONField(blank=True, default=list)),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lot_size_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('lot_size_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bedroom_min', models.IntegerField(blank=True, null=True)),
                ('bathroom_min', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('sqft_min', models.IntegerField(blank=True, null=True)),
                ('sqft_max', models.IntegerField(blank=True, null=True)),
                ('year_built_min', models.IntegerField(blank=True, null=True)),
                ('year_built_max', models.IntegerField(blank=True, null=True)),
                ('restricted_rehabs', models.JSONField(blank=True, default=list)),
                ('specialty_rehab_avoidance', models.JSONField(blank=True, default=list)),
                ('strict_requirements', models.JSONField(blank=True, default=list)),
                ('location_characteristics', models.JSONField(blank=True, default=list)),
                ('property_characteristics', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, null=True)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buy_box', to='buyer.buyerprofile')),
            ],
        ),
    ]
