# Generated by Django 5.2.4 on 2025-08-04 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('buyer', '0003_buyboxfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyboxfilter',
            name='access_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.accesstype'),
        ),
        migrations.AddField(
            model_name='buyboxfilter',
            name='land_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.landtype'),
        ),
    ]
