# Generated by Django 5.2.4 on 2025-08-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_buyboxfilter_access_type_buyboxfilter_land_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyboxfilter',
            name='zoning',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
