# Generated by Django 5.2.4 on 2025-08-08 09:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_buyboxfilter_zoning'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyboxfilter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyboxfilter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='buyboxfilter',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal admin notes', null=True),
        ),
        migrations.AlterField(
            model_name='buyboxfilter',
            name='zoning',
            field=models.JSONField(blank=True, default=list, help_text='List of acceptable zoning types'),
        ),
    ]
