# Generated by Django 5.2.4 on 2025-08-09 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('buyer', '0006_buyboxfilter_created_at_buyboxfilter_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyboxfilter',
            name='preferred_utility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.utility'),
        ),
    ]
