# Generated by Django 5.2.4 on 2025-08-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0007_buyboxfilter_preferred_utility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyboxfilter',
            name='preferred_cities',
        ),
        migrations.RemoveField(
            model_name='buyboxfilter',
            name='preferred_counties',
        ),
        migrations.RemoveField(
            model_name='buyboxfilter',
            name='preferred_states',
        ),
        migrations.RemoveField(
            model_name='buyboxfilter',
            name='preferred_zip_codes',
        ),
        migrations.AddField(
            model_name='buyboxfilter',
            name='address',
            field=models.CharField(default='', max_length=500),
        ),
    ]
