# Generated by Django 5.2.4 on 2025-08-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_remove_buyboxfilter_preferred_cities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyboxfilter',
            name='address',
            field=models.CharField(max_length=500),
        ),
    ]
