# Generated by Django 5.2.4 on 2025-08-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0009_alter_buyboxfilter_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyboxfilter',
            name='exit_strategy',
            field=models.CharField(choices=[('infill', 'Infill Lot Development'), ('flip', 'Buy & Flip'), ('subdivide', 'Subdivide & Sell'), ('seller_financing', 'Seller Financing'), ('rezoning', 'Entitlement/Rezoning'), ('mobile_home', 'Mobile Home Lot')], default='flip', max_length=30),
        ),
    ]
