# Generated by Django 5.2.4 on 2025-08-21 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0012_alter_buyboxfilter_exit_strategy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyboxfilter',
            name='exit_strategy',
        ),
    ]
