# Generated by Django 5.2.4 on 2025-08-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0013_remove_buyboxfilter_exit_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyboxfilter',
            name='exit_strategy',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
