# Generated by Django 5.2.4 on 2025-08-21 15:07

from django.db import migrations
from django.db import models
import json

def convert_exit_strategy_to_json(apps, schema_editor):
    """
    Convert existing exit_strategy string values to JSON list format
    """
    BuyBoxFilter = apps.get_model('buyer', 'BuyBoxFilter')  # Replace 'your_app_name' with actual app name
    
    for buybox in BuyBoxFilter.objects.all():
        if buybox.exit_strategy:
            # If it's already a list (shouldn't happen but safety check)
            if isinstance(buybox.exit_strategy, list):
                continue
            
            # If it's a string, convert to list
            if isinstance(buybox.exit_strategy, str):
                # Handle single strategy
                buybox.exit_strategy = [buybox.exit_strategy]
                buybox.save()
            else:
                # If it's None or empty, set to empty list
                buybox.exit_strategy = []
                buybox.save()

def reverse_exit_strategy_to_string(apps, schema_editor):
    """
    Reverse migration: Convert JSON list back to string (first item)
    """
    BuyBoxFilter = apps.get_model('buyer', 'BuyBoxFilter')
    
    for buybox in BuyBoxFilter.objects.all():
        if buybox.exit_strategy and isinstance(buybox.exit_strategy, list):
            # Take the first strategy if multiple exist
            if len(buybox.exit_strategy) > 0:
                buybox.exit_strategy = buybox.exit_strategy[0]
            else:
                buybox.exit_strategy = ''
            buybox.save()

class Migration(migrations.Migration):
    
    dependencies = [
        ('buyer', '0016_alter_buyboxfilter_exit_strategy'),
    ]

    operations = [
        # Step 1: Add a temporary field
        migrations.AddField(
            model_name='buyboxfilter',
            name='exit_strategy_temp',
            field=models.JSONField(default=list, blank=True),
        ),
        
        # Step 2: Convert data
        migrations.RunPython(
            convert_exit_strategy_to_json,
            reverse_exit_strategy_to_string
        ),
        
        # Step 3: Remove old field
        migrations.RemoveField(
            model_name='buyboxfilter',
            name='exit_strategy',
        ),
        
        # Step 4: Rename temp field to original name
        migrations.RenameField(
            model_name='buyboxfilter',
            old_name='exit_strategy_temp',
            new_name='exit_strategy',
        ),
    ]