# Generated by Django 5.2.4 on 2025-08-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0017_auto_20250821_2037'),
    ]

    operations = [
    ]
