# Generated by Django 5.2.4 on 2025-08-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0017_auto_20250821_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyboxfilter',
            name='exit_strategy',
        ),
    ]
