# Generated by Django 5.2.4 on 2025-08-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0018_auto_20250821_2040'),
        ('buyer', '0018_remove_buyboxfilter_exit_strategy'),
    ]

    operations = [
    ]
