# Generated by Django 5.2.4 on 2025-08-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0019_merge_20250822_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyboxfilter',
            name='exit_strategy',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
