# Generated by Django 5.2.4 on 2025-08-22 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0020_buyboxfilter_exit_strategy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyboxfilter',
            name='land_type',
        ),
    ]
