# Generated by Django 5.2.4 on 2025-09-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0021_remove_buyboxfilter_land_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofile',
            name='ghl_contact_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
