# Generated by Django 5.2.4 on 2025-09-04 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0022_buyerprofile_ghl_contact_id'),
        ('data_management_app', '0014_remove_propertysubmission_development_costs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerDealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('declined', 'Declined'), ('offer_made', 'Offer Made'), ('under_contract', 'Under Contract'), ('accepted', 'Accepted')], default='sent', max_length=20)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_logs', to='buyer.buyerprofile')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_logs', to='data_management_app.propertysubmission')),
            ],
            options={
                'ordering': ['-sent_date'],
            },
        ),
    ]
