# Generated by Django 5.2.4 on 2025-09-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0023_buyerdeallog'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerdeallog',
            name='reject_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
