# Generated by Django 5.2.4 on 2025-07-22 13:52

import data_management_app.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=500)),
                ('acreage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zoning', models.CharField(max_length=100)),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_aev', models.DecimalField(decimal_places=2, help_text='Estimated Assessed Evaluated Value', max_digits=12)),
                ('development_costs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('topography', models.TextField()),
                ('environmental_factors', models.TextField()),
                ('nearest_attraction', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('access_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.accesstype')),
                ('land_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.landtype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_properties', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_submissions', to=settings.AUTH_USER_MODEL)),
                ('utilities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.utility')),
            ],
            options={
                'verbose_name': 'Property Submission',
                'verbose_name_plural': 'Property Submissions',
                'db_table': 'property_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=data_management_app.models.property_file_upload_path, validators=[data_management_app.models.validate_file_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'mp4', 'kml', 'dwg', 'dxf', 'step', 'stp'])])),
                ('file_type', models.CharField(choices=[('image', 'Image (JPG/PNG)'), ('pdf', 'PDF Document'), ('video', 'Video (MP4)'), ('kml', 'KML File'), ('cad', 'CAD File'), ('other', 'Other')], max_length=10)),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='data_management_app.propertysubmission')),
            ],
            options={
                'verbose_name': 'Property File',
                'verbose_name_plural': 'Property Files',
                'db_table': 'property_files',
                'ordering': ['created_at'],
            },
        ),
    ]
