# Generated by Django 5.2.4 on 2025-07-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0002_conversationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysubmission',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
