# Generated by Django 5.2.4 on 2025-07-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0003_propertysubmission_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertysubmission',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='propertysubmission',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True),
        ),
    ]
