# Generated by Django 5.2.4 on 2025-08-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0004_alter_propertysubmission_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysubmission',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='has_clear_title',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='has_hoa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='has_legal_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='has_paved_road_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='in_flood_zone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='location_characteristics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='mobile_home_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='property_characteristics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='utilities_at_road',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
