# Generated by Django 5.2.4 on 2025-08-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0005_propertysubmission_city_propertysubmission_county_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertysubmission',
            name='city',
        ),
        migrations.RemoveField(
            model_name='propertysubmission',
            name='county',
        ),
        migrations.RemoveField(
            model_name='propertysubmission',
            name='has_clear_title',
        ),
        migrations.RemoveField(
            model_name='propertysubmission',
            name='has_hoa',
        ),
        migrations.RemoveField(
            model_name='propertysubmission',
            name='has_legal_access',
        ),
        migrations.RemoveField(
            model_name='propertysubmission',
            name='has_paved_road_access',
        ),
        migrations.RemoveField(
            model_name='propertysubmission',
            name='in_flood_zone',
        ),
        migrations.RemoveField(
            model_name='propertysubmission',
            name='mobile_home_allowed',
        ),
        migrations.RemoveField(
            model_name='propertysubmission',
            name='state',
        ),
        migrations.RemoveField(
            model_name='propertysubmission',
            name='utilities_at_road',
        ),
        migrations.RemoveField(
            model_name='propertysubmission',
            name='zip_code',
        ),
    ]
