# Generated by Django 5.2.4 on 2025-08-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0006_remove_propertysubmission_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysubmission',
            name='agreed_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='exit_strategy',
            field=models.CharField(choices=[('infill', 'Infill Lot Development'), ('flip', 'Buy & Flip'), ('subdivide', 'Subdivide & Sell'), ('seller_financing', 'Seller Financing'), ('rezoning', 'Entitlement/Rezoning'), ('mobile_home', 'Mobile Home Lot')], default='flip', max_length=30),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='extra_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='llc_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='lot_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='lot_size_unit',
            field=models.CharField(choices=[('acres', 'Acres'), ('sqft', 'Square Feet')], default='acres', max_length=10),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='parcel_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='propertysubmission',
            name='under_contract',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3),
        ),
    ]
