# Generated by Django 5.2.4 on 2025-08-18 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0007_propertysubmission_agreed_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertysubmission',
            name='asking_price',
        ),
        migrations.AlterField(
            model_name='propertysubmission',
            name='agreed_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='propertysubmission',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='propertysubmission',
            name='exit_strategy',
            field=models.CharField(choices=[('infill', 'Infill Lot Development'), ('flip', 'Buy & Flip'), ('subdivide', 'Subdivide & Sell'), ('seller_financing', 'Seller Financing'), ('rezoning', 'Entitlement/Rezoning'), ('mobile_home', 'Mobile Home Lot')], max_length=30),
        ),
        migrations.AlterField(
            model_name='propertysubmission',
            name='extra_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='propertysubmission',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertysubmission',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='propertysubmission',
            name='llc_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='propertysubmission',
            name='lot_size',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='propertysubmission',
            name='lot_size_unit',
            field=models.CharField(choices=[('acres', 'Acres'), ('sqft', 'Square Feet')], max_length=10),
        ),
        migrations.AlterField(
            model_name='propertysubmission',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='propertysubmission',
            name='under_contract',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3),
        ),
    ]
