# Generated by Django 5.2.4 on 2025-08-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0008_remove_propertysubmission_asking_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertysubmission',
            name='environmental_factors',
        ),
        migrations.RemoveField(
            model_name='propertysubmission',
            name='nearest_attraction',
        ),
        migrations.RemoveField(
            model_name='propertysubmission',
            name='topography',
        ),
    ]
