# Generated by Django 5.2.4 on 2025-09-01 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0010_conversationmessage_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyfile',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
