# Generated by Django 5.2.4 on 2025-09-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0011_alter_propertyfile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyfile',
            name='description',
        ),
        migrations.AlterField(
            model_name='propertysubmission',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
