# Generated by Django 5.2.4 on 2025-09-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0012_remove_propertyfile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyfile',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
