# Generated by Django 5.2.4 on 2025-09-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0013_propertyfile_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertysubmission',
            name='development_costs',
        ),
        migrations.RemoveField(
            model_name='propertysubmission',
            name='estimated_aev',
        ),
    ]
