# Generated by Django 5.2.4 on 2025-09-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0014_remove_propertysubmission_development_costs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysubmission',
            name='buyer_rejected_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertysubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review_with_buyer', 'Under review with Buyer'), ('buyer_approved', 'Buyer Approved'), ('buyer_rejected', 'Buyer Rejected'), ('mls_pending', 'MLS Listing - Pending'), ('mls_active', 'MLS Active Listing'), ('sold', 'Sold Deal'), ('canceled', 'Canceled Deal')], default='submitted', max_length=50),
        ),
    ]
