# Generated by Django 5.2.4 on 2025-09-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management_app', '0015_propertysubmission_buyer_rejected_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertysubmission',
            name='ghl_contact_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
